export { default as LogoSustentable } from './logoSustentable.webp';
export { default as IconFacebook } from './facebook.webp';
export { default as IconInstagram } from './instagram.webp';
export { default as IconLinkedIn } from './linkedin.webp';
export { default as IconConfianza } from './confianza.webp';
export { default as IconSolidaridad } from './solidaridad.webp';
export { default as IconRespeto } from './respeto.webp';
export { default as IconRigurosidad } from './rigurosidad.webp';
export { default as IconTransparencia } from './transparencia.webp';